name: stock_prediction
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  curved_navigation_bar: ^1.0.3
  anim_search_bar: ^2.0.2
  cupertino_icons: ^1.0.2
  scrollable_positioned_list: ^0.3.5
  http: ^0.13.5
  lottie: ^2.2.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/imgs/
    - assets/anim/
